<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SupportedOSPlatformVersion>10.0.14393.0</SupportedOSPlatformVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <Version>1.0.0</Version>
    <AssemblyName>3x3Centar.Scoreboard</AssemblyName>
    <RootNamespace>ThreeByThree.Centar.Scoreboard.Wpf</RootNamespace>
    <Product>3x3 Centar Scoreboard</Product>
    <Company>3x3 Centar</Company>
    <Authors>3x3 Centar</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ThreeByThree.Centar.Scoreboard.Application\ThreeByThree.Centar.Scoreboard.Application.csproj" />
    <ProjectReference Include="..\ThreeByThree.Centar.Scoreboard.Infrastructure\ThreeByThree.Centar.Scoreboard.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Branding\3x3logo.png" />
    <Resource Include="Assets\Fonts\*.otf" />
  </ItemGroup>

</Project>
